# Задание на повторение материала

In [3]:
import numpy as np

# Задание 1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

# Задание 2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [4]:
a1 = a.reshape(2, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
a2 = a.reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
a3 = a.reshape(4, 3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [9]:
a4 = a.reshape(6, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [10]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

# Задание 3
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [11]:
a1 = a.reshape(2, -1)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [12]:
a2 = a.reshape(3, -1)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
a3 = a.reshape(12, -1)
a3

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [14]:
a4 = a.reshape(-1, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [15]:
a1 = a.reshape(-1, 3)
a1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

# Задание 4
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

По результатам последнего примера из задания 2 можно заметить, что элементом такого массива является список, что не соответствует одномерному массиву (задание 1). Следовательно, такой массив numpy нельзя назвать одномерным.

# Задание 5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [6]:
a = np.random.sample((3, 4))
b = a.flatten()
b

array([0.24204138, 0.10872405, 0.08406255, 0.74633504, 0.21056772,
       0.64209801, 0.54006135, 0.83585429, 0.2758469 , 0.78338876,
       0.97905036, 0.9878571 ])

# Задание 6
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [9]:
a = np.arange(20,  0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

# Задание 7
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [11]:
b = np.arange(20,  0, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Массив a - одномерный, b - двумерный

# Задание 8
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [43]:
a = np.zeros((2, 2))
b = np.ones((a.shape[0]+1, a.shape[1]))
v = np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
v.size

10

# Задание 9
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [35]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At)
B.shape
np.linalg.det(B)

0.0

Найти обратную матрицу не получится, т.к. матрица B - вырожденная (определитель равен 0)

# Задание 10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [74]:
np.random.seed(42)

# Задание 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [84]:
c = np.random.randint(0, 16, 16)
print(c)

[ 1  3  8 11 13  1  9  8  9  4  1  3 11 14 11  6]


# Задание 12
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [85]:
C = c.reshape(int(np.sqrt(c.size)), -1)
D = B + C*10
det = np.linalg.det(D)
rank = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
print(f'Определитель: {det}; ранг: {rank}')
print('Обратная матрица:')
print(D_inv)

Определитель: -131179000.0000003; ранг: 4
Обратная матрица:
[[-0.01288362  0.0059633   0.0049479  -0.0015815 ]
 [-0.00987109 -0.00748153  0.00457909  0.00498571]
 [ 0.00448502  0.00845151 -0.0201857   0.00701896]
 [ 0.00820863 -0.00444202  0.0127002  -0.00646902]]


# Задание 13
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [88]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[0., 1., 1., 0.],
       [0., 0., 1., 1.],
       [1., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [93]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [94]:
C

array([[ 1,  3,  8, 11],
       [13,  1,  9,  8],
       [ 9,  4,  1,  3],
       [11, 14, 11,  6]])

In [92]:
E = np.zeros((4,4))
E[np.where(D_inv == 1)] = B[np.where(D_inv == 1)]
E[np.where(D_inv == 0)] = C[np.where(D_inv == 0)]
E

array([[  1.,  14.,  23.,  11.],
       [ 13.,   1.,  86., 122.],
       [ 23.,  86.,   1., 212.],
       [ 32.,  14., 212.,   6.]])